backend:
  name: github
  repo: roughcompass/amyandmartin
  site_domain: location.hippobyte
  branch: master
  commit_messages:
    create: 'Create {{collection}} "{{slug}}”'
    update: 'Update {{collection}} "{{slug}}”'
    delete: 'Delete {{collection}} "{{slug}}”'
    uploadMedia: '[skip ci] Upload "{{path}}”'
    deleteMedia: '[skip ci] Delete "{{path}}”'

media_folder: static/content/media
public_folder: "../media/"

collections: 
  - name: "pages"
    label: "Pages"
    files: [
      {
        file: "static/content/pages/index.json",
        label: "Home Page",
        name: "index",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/"},
          {label: "Translations", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
        ]
      },
      {
        file: "static/content/pages/story.json",
        label: "Our Story Page",
        name: "story",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "story"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/story"},
          {label: "Translations", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 1},
        ]
      },
      {
        file: "static/content/pages/travel.json",
        label: "Travel Page",
        name: "travel",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "travel"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/travel"},
          {label: "Translations", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 2},
        ]
      },
      {
        file: "static/content/pages/activities.json",
        label: "Acitivities Page",
        name: "activities",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "activities"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/activities"},
          {label: "Translations", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 3},
        ]
      },
      {
        file: "static/content/pages/photos.json",
        label: "Photos Page",
        name: "photos",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "photos"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/photos"},
          {label: "Translations", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 4},
        ]
      }
    ]

  - name: "settings"
    label: "Wedding Settings"
    folder: "static/content/settings"
    extension: "json"
    create: false
    slug: "wedding-settings"
    filter: {field: "templateKey", value: "wedding-settings"}
    summary: "{{title}}"
    sortableFields: ['connector', 'title', 'date', 'commit_date']
    fields: [
      {label: "Template Key", name: "templateKey", widget: "hidden", default: "wedding-settings"},
      {label: "Couple", hint: "ex. Amy & Martin", name: "title", widget: "string"},
      {label: "Location", hint: "ex. San Diego, CA", name: "location", widget: "string"},
      {label: "Ceremony Date", name: "ceremonyDate", widget: "date"}
    ]

  - name: "language"  
    label: "Language Options"
    folder: "static/content/settings"
    extension: "json"
    create: true
    slug: "{{slug}}"
    filter: {field: "templateKey", value: "language-settings"}
    summary: "{{title}} - {{description}}"
    sortableFields: ['title', 'description', commit_date']
    fields: [
      {label: "Template Key", name: "templateKey", widget: "hidden", default: "language-settings"},
      {label: "Language", name: "title", widget: "string"},
      {label: "Locale", hint: "see https://www.science.co.il/language/Locale-codes.php", default: 'en', name: "locale", widget: "string"},
      {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
      {label: "Default", name: "default", widget: "boolean", default: false},
      {label: "Translations", name: "translations", widget: "list", summary: '{{fields.languageTitle}} - {{fields.translation}}', minimize_collapsed: true, fields: [
        {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
        {label: "Translation", name: "translation", widget: "string"},
      ]}
    ]