backend:
  name: github
  repo: roughcompass/amyandmartin
  site_domain: location.hostname
  branch: master
  commit_messages:
    create: 'Create {{collection}} "{{slug}}”'
    update: 'Update {{collection}} "{{slug}}”'
    delete: 'Delete {{collection}} "{{slug}}”'
    uploadMedia: '[skip ci] Upload "{{path}}”'
    deleteMedia: '[skip ci] Delete "{{path}}”'

media_folder: static/content/media
public_folder: "../media/"

collections:
  - name: "pages"
    label: "Pages"
    files: [
      {
        file: "static/content/pages/index.json",
        label: "Home Page",
        name: "index",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
          {label: "Page Sections", name: "sections", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
            {label: Primary Image, name: featuredimage, widget: image},
            {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
            {label: "Content", name: "content", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
              {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "markdown"}
            ]}
          ]}
        ]
      },
      {
        file: "static/content/pages/story.json",
        label: "Our Story Page",
        name: "story",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "story"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/story"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Description", name: "description", widget: "markdown"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 1},
          {label: "Page Sections", name: "sections", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
            {label: Primary Image, name: featuredimage, widget: image},
            {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
            {label: "Content", name: "content", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
              {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "markdown"}
            ]}
          ]}
        ]
      },
      {
        file: "static/content/pages/travel.json",
        label: "Travel Page",
        name: "travel",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "travel"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/travel"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Description", name: "description", widget: "markdown"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 2},
          {label: "Page Sections", name: "sections", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
            {label: Primary Image, name: featuredimage, widget: image},
            {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
            {label: "Content", name: "content", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
              {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "markdown"}
            ]}
          ]}
        ]
      },
      {
        file: "static/content/pages/activities.json",
        label: "Acitivities Page",
        name: "activities",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "activities"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/activities"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Description", name: "description", widget: "markdown"},
          ]},
          {label: Primary Image, name: featuredimage, widget: image},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 3},
          {label: "Page Sections", name: "sections", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
            {label: Primary Image, name: featuredimage, widget: image},
            {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
            {label: "Content", name: "content", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
              {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "markdown"}
            ]}
          ]}
        ]
      },
      {
        file: "static/content/pages/covid.json",
        label: "Covid Page",
        name: "covid",
        fields: [
          { label: "Template Key", name: "templateKey", widget: "hidden", default: "covid" },
          { label: "Page Path", name: "path", widget: "hidden", default: "/covid" },
          { label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            { label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: [ "title" ], valueField: "title" },
            { label: "Title", name: "title", widget: "string" },
            { label: "Menu Title", name: "menuTitle", widget: "string" },
          ] },
          { label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            { label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: [ "title" ], valueField: "title" },
            { label: "Description", name: "description", widget: "markdown" },
          ] },
          { label: Primary Image, name: featuredimage, widget: image },
          { label: "Order", name: "order", widget: "number", valueType: "int", default: 3 },
          { label: "Page Sections", name: "sections", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
            { label: Primary Image, name: featuredimage, widget: image },
            { label: "Order", name: "order", widget: "number", valueType: "int", default: 0 },
            { label: "Content", name: "content", widget: "list", summary: '{{fields.title}}', minimize_collapsed: true, fields: [
              { label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: [ "title" ], valueField: "title" },
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "markdown" }
            ] }
          ] }
        ]
      },
      {
        file: "static/content/pages/photos.json",
        label: "Photos Page",
        name: "photos",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "photos"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/photos"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Description", name: "description", widget: "markdown"},
          ]},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 4},
          { label: "Gallery", name: "gallery", widget: "list", fields: [
            { label: Primary Image, name: featuredimage, widget: image }
          ] }
        ]
      },
      {
        file: "static/content/pages/rsvp.json",
        label: "RSVP Page",
        name: "rsvp",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "rsvp"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/rsvp"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Description", name: "description", widget: "markdown"},
          ]},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 5}
        ]
      },
      {
        file: "static/content/pages/rsvp-confirm.json",
        label: "RSVP Confirm Page",
        name: "confirm",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "rsvp"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/rsvp"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Description", name: "description", widget: "markdown"},
          ]},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 5}
        ]
      },
      {
        file: "static/content/pages/rsvp-decline.json",
        label: "RSVP Decline Page",
        name: "decline",
        fields: [
          {label: "Template Key", name: "templateKey", widget: "hidden", default: "rsvp"},
          {label: "Page Path", name: "path", widget: "hidden", default: "/rsvp"},
          {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.title}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Title", name: "title", widget: "string"},
            {label: "Menu Title", name: "menuTitle", widget: "string"},
          ]},
          {label: "Page Description", name: "descriptions", widget: "list", summary: '{{fields.description}} - {{fields.languageTitle}}', minimize_collapsed: true, fields: [
            {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
            {label: "Description", name: "description", widget: "markdown"},
          ]},
          {label: "Order", name: "order", widget: "number", valueType: "int", default: 5}
        ]
      }
    ]

  - name: "settings"
    label: "Wedding Settings"
    folder: "static/content/settings"
    extension: "json"
    create: false
    slug: "wedding-settings"
    filter: {field: "templateKey", value: "wedding-settings"}
    summary: "{{title}}"
    sortableFields: ['connector', 'title', 'date', 'commit_date']
    fields: [
      {label: "Template Key", name: "templateKey", widget: "hidden", default: "wedding-settings"},
      {label: "Couple", hint: "ex. Amy & Martin", name: "title", widget: "string"},
      {label: "Location", hint: "ex. San Diego, CA", name: "location", widget: "string"},
      {label: "Location Detail", name: "locationDetail", widget: "string", required: false },
      {label: "Directions", hint: "ex. Google Mamps link", name: "directions", widget: "string", required: false},
      {label: "Ceremony Date", name: "ceremonyDate", widget: "date"},
      {label: "RSVP Date", name: "rsvpDate", widget: "date"}
    ]

  - name: "language"
    label: "Language Options"
    folder: "static/content/settings"
    extension: "json"
    create: true
    slug: "{{slug}}"
    filter: {field: "templateKey", value: "language-settings"}
    summary: "{{title}} - {{description}}"
    sortableFields: ['title', 'description', commit_date']
    fields: [
      {label: "Template Key", name: "templateKey", widget: "hidden", default: "language-settings"},
      {label: "Language", name: "title", widget: "string"},
      {label: "Locale", hint: "see https://www.science.co.il/language/Locale-codes.php", default: 'en', name: "locale", widget: "string"},
      {label: "Order", name: "order", widget: "number", valueType: "int", default: 0},
      {label: "Default", name: "default", widget: "boolean", default: false},
      {label: "Page Title", name: "translations", widget: "list", summary: '{{fields.languageTitle}} - {{fields.translation}}', minimize_collapsed: true, fields: [
        {label: "Language", name: "languageTitle", widget: "relation", collection: "language", searchFields: ["title"], valueField: "title"},
        {label: "Translation", name: "translation", widget: "string"},
      ]}
    ]

  - name: "translations"
    label: "Translation"
    folder: "static/content/translations"
    extension: "json"
    create: true
    slug: "{{slug}}"
    filter: {field: "templateKey", value: "translations"}
    summary: "{{title}}"
    sortableFields: ['title', commit_date']
    fields: [
      {label: "Template Key", name: "templateKey", widget: "hidden", default: "translations"},
      {label: "Term", name: "title", widget: "string"},
      {label: "Translations", name: "translations", widget: "list", summary: '{{fields.locale}} - {{fields.translation}}', fields: [
        {label: "Locale", name: "locale", widget: "relation", collection: "language", searchFields: ["title"], valueField: "locale"},
        {label: "Translation", name: "translation", widget: "string"},
      ]}
    ]

  - name: "wedding-day"
    label: "Day of Wedding"
    folder: "static/content/settings"
    extension: "json"
    create: true
    slug: "{{slug}}"
    filter: { field: "templateKey", value: "wedding-day" }
    summary: "{{title}}"
    sortableFields: [ 'title', commit_date' ]
    fields: [
      { label: "Template Key", name: "templateKey", widget: "hidden", default: "wedding-day" },
      { label: "Order", name: "order", widget: "number" },
      { label: "Event", name: "title", widget: "string" },
      { label: "Start", name: "startTime", widget: "string" },
      { label: "End", name: "endTime", widget: "string" },
      { label: "Location", name: "location", widget: "string", required: false },
      { label: "Directions", name: "directions", widget: "string", required: false },
    ]
